name: SgpViz
version: 0.999.2
date: 2018-09-26
description: |
    A package for semigroup visualization

authors:
    - name: Manuel Delgado
      url: http://www.fc.up.pt/cmup/mdelgado/
    - name: Jose Morais

maintainers:
    - name: Manuel Delgado
      url: http://www.fc.up.pt/cmup/mdelgado/

GAP: ">=4.4"

needed-pkgs:
    - name: "Automata"
      version: ">= 1.11"
      url: "http://www.fc.up.pt/cmup/mdelgado/automata"

www: https://gap-packages.github.io/sgpviz
readme: README.md
packageinfo: https://gap-packages.github.io/sgpviz/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/sgpviz/releases/download/v0.999.2/SgpViz-0.999.2.tar.gz

abstract: |
    The <span class="pkgname">SgpViz</span> package, is a package with some visualization features for finite semigroups.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
